export const moodData = [
  { day: "Mon", mood: 4, date: "2025-11-16" },
  { day: "Tue", mood: 3, date: "2025-11-17" },
  { day: "Wed", mood: 3, date: "2025-11-18" },
  { day: "Thu", mood: 5, date: "2025-11-19" },
  { day: "Fri", mood: 4, date: "2025-11-20" },
  { day: "Sat", mood: 2, date: "2025-11-21" },
  { day: "Sun", mood: 3, date: "2025-11-22" },
];

export const wellnessActivities = [
  {
    id: 1,
    category: "Mindfulness",
    title: "Box Breathing",
    description: "Calm your nervous system with 4-4-4-4 breathing",
    duration: "5 min",
    difficulty: "Easy",
    icon: "🫁",
    instructions: [
      "Find a comfortable seated position",
      "Breathe in slowly through your nose for 4 counts",
      "Hold your breath for 4 counts",
      "Breathe out slowly through your mouth for 4 counts",
      "Hold empty for 4 counts",
      "Repeat for 5 minutes",
    ],
  },
  {
    id: 2,
    category: "Mindfulness",
    title: "Body Scan Meditation",
    description: "Progressive relaxation from head to toe",
    duration: "10 min",
    difficulty: "Easy",
    icon: "🧘",
    instructions: [
      "Lie down or sit comfortably",
      "Close your eyes and take three deep breaths",
      "Start at the top of your head, notice any tension",
      "Slowly move your attention down through your body",
      "Relax each part as you notice it",
      "End at your toes, feeling completely relaxed",
    ],
  },
  {
    id: 3,
    category: "Mindfulness",
    title: "Mindful Walking",
    description: "Notice your surroundings with all five senses",
    duration: "15 min",
    difficulty: "Easy",
    icon: "🚶",
    instructions: [
      "Find a safe, peaceful place to walk",
      "Walk at a natural, comfortable pace",
      "Notice 5 things you can see",
      "Notice 4 things you can touch or feel",
      "Notice 3 things you can hear",
      "Notice 2 things you can smell",
      "Notice 1 thing you can taste",
      "Return your attention to your breath if your mind wanders",
    ],
  },
  {
    id: 4,
    category: "Exercise",
    title: "Gentle Stretching",
    description: "Release tension in your neck, shoulders, and back",
    duration: "10 min",
    difficulty: "Easy",
    icon: "🤸",
    instructions: [
      "Start with neck rolls - 5 in each direction",
      "Shoulder shrugs - lift and release 10 times",
      "Arm circles - 10 forward, 10 backward",
      "Side stretches - reach overhead and lean left, then right",
      "Seated twist - gently twist your torso in each direction",
      "Cat-cow stretch if you're able to get on the floor",
    ],
  },
  {
    id: 5,
    category: "Exercise",
    title: "Dance Break",
    description: "Move to your favorite upbeat song",
    duration: "5 min",
    difficulty: "Easy",
    icon: "💃",
    instructions: [
      "Put on your favorite energetic song",
      "Start moving however feels good",
      "Let yourself be silly and free",
      "Focus on the joy of movement, not perfection",
      "Keep moving for the entire song",
      "Notice how you feel afterward",
    ],
  },
  {
    id: 6,
    category: "Exercise",
    title: "Nature Walk",
    description: "Fresh air and movement boost mood",
    duration: "20 min",
    difficulty: "Medium",
    icon: "🌳",
    instructions: [
      "Find a nearby park or natural area",
      "Walk at a comfortable pace",
      "Take deep breaths of fresh air",
      "Notice the colors, sounds, and smells around you",
      "Try to stay present in the moment",
      "Walk for at least 20 minutes",
    ],
  },
  {
    id: 7,
    category: "Self-Care",
    title: "Gratitude Journal",
    description: "Write 3 things you're grateful for today",
    duration: "5 min",
    difficulty: "Easy",
    icon: "📝",
    instructions: [
      "Find a quiet comfortable space",
      "Think about your day so far",
      "Write down 3 things you're grateful for",
      "They can be big or small",
      "Reflect on why each one matters to you",
      "Notice how this practice makes you feel",
    ],
  },
  {
    id: 8,
    category: "Self-Care",
    title: "Digital Detox",
    description: "Take a break from screens",
    duration: "30 min",
    difficulty: "Medium",
    icon: "📵",
    instructions: [
      "Set a timer for 30 minutes",
      "Put your phone and devices away",
      "Choose an offline activity you enjoy",
      "Read a book, draw, or spend time in nature",
      "Notice any urges to check your phone",
      "Observe how you feel without digital distractions",
    ],
  },
  {
    id: 9,
    category: "Self-Care",
    title: "Creative Expression",
    description: "Draw, color, or doodle freely",
    duration: "15 min",
    difficulty: "Easy",
    icon: "🎨",
    instructions: [
      "Gather paper and coloring materials",
      "Set a timer for 15 minutes",
      "Draw or color without any goal in mind",
      "Let your hand move freely",
      "Don't judge your creation",
      "Focus on the process, not the result",
    ],
  },
  {
    id: 10,
    category: "Social",
    title: "Reach Out to a Friend",
    description: "Connect with someone you care about",
    duration: "15 min",
    difficulty: "Easy",
    icon: "💬",
    instructions: [
      "Think of someone you'd like to connect with",
      "Send them a text, call, or video chat",
      "Ask how they're doing",
      "Share something positive from your day",
      "Listen actively to their response",
      "Schedule a time to connect again soon",
    ],
  },
  {
    id: 11,
    category: "Social",
    title: "Write a Thank You Note",
    description: "Express appreciation to someone",
    duration: "10 min",
    difficulty: "Easy",
    icon: "💌",
    instructions: [
      "Think of someone who has helped you recently",
      "Write them a heartfelt thank you message",
      "Be specific about what you're grateful for",
      "Explain how their actions made you feel",
      "Send the message",
      "Notice how expressing gratitude feels",
    ],
  },
  {
    id: 12,
    category: "Journaling",
    title: "Stream of Consciousness",
    description: "Write whatever comes to mind",
    duration: "10 min",
    difficulty: "Easy",
    icon: "✍️",
    instructions: [
      "Set a timer for 10 minutes",
      "Start writing and don't stop",
      "Write whatever thoughts come to mind",
      "Don't worry about grammar or making sense",
      "Let your thoughts flow onto the page",
      "Read back what you wrote when done (optional)",
    ],
  },
  {
    id: 13,
    category: "Journaling",
    title: "Worry Dump",
    description: "Get anxious thoughts out of your head",
    duration: "10 min",
    difficulty: "Easy",
    icon: "🗑️",
    instructions: [
      "Make a list of everything that's worrying you",
      "Write quickly without overthinking",
      "Include big worries and small ones",
      "When the list is complete, take a deep breath",
      "For each worry, ask: Can I do something about this now?",
      "Set aside worries you can't control",
    ],
  },
  {
    id: 14,
    category: "Journaling",
    title: "Future Self Letter",
    description: "Write to yourself one year from now",
    duration: "15 min",
    difficulty: "Medium",
    icon: "📬",
    instructions: [
      "Imagine yourself one year from today",
      "Write a letter to that future you",
      "Share your current hopes and dreams",
      "Describe challenges you're facing now",
      "Offer yourself encouragement",
      "Save it to read in one year",
    ],
  },
];

export const aiResponses = [
  "Thank you for sharing that with me. It takes courage to open up about how you're feeling.",
  "I hear you. It sounds like you're going through a challenging time. What kind of support would be most helpful right now?",
  "That's a completely valid feeling. Would you like to try a quick calming exercise together?",
  "I'm here to listen. Sometimes it helps just to express what's on your mind. Feel free to share as much or as little as you'd like.",
  "It sounds like you're experiencing a lot right now. Remember that it's okay to feel this way, and you're not alone.",
  "That must be difficult. Have you tried any coping strategies that have helped you in the past?",
  "Thank you for trusting me with this. Your feelings are important and valid.",
  "It's wonderful that you're reaching out. Taking care of your mental health is a sign of strength.",
];

export const journalEntries = [
  {
    id: 1,
    date: "2025-11-21",
    mood: 2,
    content: "Today was tough, but I managed to complete my breathing exercise. Feeling a bit better now. Sometimes the small wins matter most.",
  },
  {
    id: 2,
    date: "2025-11-19",
    mood: 5,
    content: "Had a great conversation with a friend today. Realized how much I needed that connection. Feeling grateful for the people in my life.",
  },
  {
    id: 3,
    date: "2025-11-17",
    mood: 3,
    content: "Struggled with anxiety this morning. The grounding exercise helped me feel present. Taking it one moment at a time.",
  },
];

export const crisisHelplines = [
  {
    name: "Tele MANAS",
    subtitle: "Government Mental Health Helpline",
    phone: "14416",
    description: "Free 24/7 mental health support in multiple Indian languages",
    languages: "Hindi, English, and regional languages",
    availability: "24/7",
  },
  {
    name: "Vandrevala Foundation",
    subtitle: "Mental Health Support",
    phone: "+91-9999 666 555",
    description: "Free and confidential mental health support",
    languages: "Multiple languages",
    availability: "24/7 via call, SMS, and email",
    hasText: true,
  },
  {
    name: "KIRAN Mental Health Helpline",
    subtitle: "Ministry of Social Justice",
    phone: "1800-599-0019",
    description: "Ministry of Social Justice and Empowerment helpline",
    languages: "13 Indian languages",
    availability: "24/7",
  },
  {
    name: "iCall Psychosocial Helpline",
    subtitle: "TISS Mental Health",
    phone: "9152987821",
    description: "Professional counseling support",
    email: "icall@tiss.edu",
    availability: "Monday to Saturday, 8 AM to 10 PM",
  },
];

export const stateHelplines = [
  {
    state: "Mumbai",
    name: "Connecting NGO",
    phone: "+91-9922001122 / +91-9922004305",
    availability: "24/7",
  },
  {
    state: "Delhi",
    name: "Aasra",
    phone: "+91-9820466726",
    availability: "24/7 crisis helpline",
  },
  {
    state: "Bangalore",
    name: "Parivarthan",
    phone: "+91-7676602602",
    availability: "24/7",
  },
  {
    state: "Chennai",
    name: "Sneha Foundation",
    phone: "+91-44-24640050",
    availability: "24/7",
  },
  {
    state: "Kolkata",
    name: "Samaritans",
    phone: "+91-33-2474 4704",
    availability: "24/7",
  },
];
